TemplateVector: sort fails without operator<() definition
Solution to Pohl Chapter 7 Exercise 11, which requires a demonstration
that sorting fails without a definition of operator<().

I had thought that sorting Complex objects without an explicitly
defined operator<() would fail, but that is mysteriously not the case.
Instead, here is a demonstration that sorting Polynomial objects
fails:

 /usr/include/c++/9/bits/predefined_ops.h:43:23: error: no match for
 ‘operator<’ (operand types are ‘polynomial::Polynomial’ and
 ‘polynomial::Polynomial’)

Polynomial objects are composed of Term objects.  In order to get the
template_vector_lib_test to fail, I had to first define operator==() for
Polynomials.  Polynomial's operator==() called itself, a problem which I
solved by defining operator==() for Term.  Since a Term is a degenerate
Polynomial, this recursion makes sense.  Somehow the compiler is smart
enough to select the Term operator==() once one exists.

Further, I had to define copy assignment operator=(const Polynomial&)
and operator=(const Term&).  Meanwhile I noticed that the move
assignment test for Polynomial was broken, and had to write new tests
for both Polynomial and Term.  Since the Polynomial equality-check
operator now exists, I added it to other existing tests.