Makefile: do not explicitly compile template implementation headers
There is no reason to explicitly list implementation headers for template
classes explicitly in the Makefile except that it conveniently made unit tests
depend on them.  The error described below is that I need to more properly
handle dependencies in the Makefile.

When polynomial_impl.h is included in the dependency list of
template_vector_lib_test-coverage and template_vector_lib_test-debug, it also
appears in the list of targets for compiling template_vector_lib_test.   Why?

-template_vector_lib_test-coverage template_vector_lib_test-valgrind template_vector_lib_test: complex.h complex_lib.cc polynomial.h  polynomial_lib.cc term.h term_vector.h term_lib.cc term_vector_lib.cc $(GTESTLIBS)
+template_vector_lib_test-coverage template_vector_lib_test-valgrind template_vector_lib_test: complex.h complex_lib.cc polynomial.h polynomial_impl.h polynomial_lib.cc term.h term_vector.h term_lib.cc term_vector_lib.cc $(GTESTLIBS)

-template_vector_lib_test_debug: template_vector.h template_vector_lib_test.cc complex.h complex_lib.cc polynomial.h polynomial_lib.cc term.h term_vector.h term_lib.cc term_vector_lib.cc  $(GTEST_HEADERS)
+template_vector_lib_test_debug: template_vector.h template_vector_lib_test.cc complex.h complex_lib.cc polynomial.h polynomial_impl.h polynomial_lib.cc term.h term_vector.h term_lib.cc term_vector_lib.cc  $(GTEST_HEADERS)

The resulting compilation failure is:

$ make template_vector_lib_test
g++ -std=c++17 -pthread -ggdb -Wall -Wextra -Werror -g -O0 -fno-inline -fsanitize=address,undefined -I/home/alison/gitsrc/googletest/googletest/include -isystem /home/alison/gitsrc/googletest/include  -c -o template_vector_lib_test.o template_vector_lib_test.cc
/usr/bin/g++ -std=c++17 -pthread -ggdb -Wall -Wextra -Werror -g -O0 -fno-inline -fsanitize=address,undefined -I/home/alison/gitsrc/googletest/googletest/include  -ggdb -g -fsanitize=address -L/home/alison/gitsrc/googletest/build/lib template_vector_lib_test.o template_vector.h complex.h complex_lib.cc polynomial.h polynomial_impl.h polynomial_lib.cc term.h term_vector.h term_lib.cc term_vector_lib.cc /home/alison/gitsrc/googletest/build/lib/libgtest.a /home/alison/gitsrc/googletest/build/lib/libgtest_main.a /home/alison/gitsrc/googletest/build/lib/libgtest.a /home/alison/gitsrc/googletest/build/lib/libgtest_main.a -o template_vector_lib_test
polynomial_impl.h:16:1: error: ‘Polynomial’ does not name a type; did you mean ‘polynomial’?
   16 | Polynomial::Polynomial(std::array<double, N> coef, std::array<int, N> expon) {
      | ^~~~~~~~~~
      | polynomial

The error only appeared when I changed TemplateVector to rely on smart pointers,
not when I earlier changed Polynomial or Term.