fix template_vector_lib_test with non-const comparison to Complex
Commit f04f6b87 "template_list: provide templated ostream extraction
operator" broke template_vector_lib_test by constifying the
operator<() comparison it requires.   Since template_vector_lib_test
sorts Complex numbers, it cannot be constified, so add a new non-const
comparison operator to the Complex class.

An alternative might have been const_cast where
template_vector_lib_impl.h calls operator<():

-    if (tv[index + 1] < tv[index]) {
+    if (const_cast<const T &>(tv[index + 1]) <
+        const_cast<const T &>(tv[index])) {

-      if ((candidate > index) && (tv[candidate] < tv[index])) {
+      if ((candidate > index) && (const_cast<const T &>(tv[candidate]) <
+                                  const_cast<const T &>(tv[index]))) {

However that triggers a linker failure that occurs outside this code:

in function `bool __gnu_cxx::__ops::_Iter_less_iter::operator()<complex::Complex*, complex::Complex*>(complex::Complex*, complex::Complex*) const':
/usr/include/c++/9/bits/predefined_ops.h:43: undefined reference to `complex::operator<(complex::Complex&, complex::Complex&)'

Presumably this failure is due to the reliance of std::sort() on operator<().