lcov: fix false errors with googletest with new flags
As reported at
https://github.com/linux-test-project/lcov/issues/192#issuecomment-1763349850,
lcov erroneously reports

     ERROR: (inconsistent) mismatched end line

for googletests.  The latest version of lcov from github
(2.1-14-g829d194) with added flags

    --rc geninfo_unexecuted_blocks=1
    --ignore mismatch
    --ignore-errors inconsistent
    -branch-coverage

suppresses these errors.   Unfortunately, code which formerly showed as 100%
covered now shows erroneously low values instead.   lcov no longer seems to be
useful with googletest.